# Site wide configuration

title: Data, etc.
locale: en_US
description: The nuts and bolts from research to policy in social sciences.
logo: #site-logo.png
search: true
url: https://tomschenkjr.github.io

# Jekyll configuration

permalink:   /:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  syntax_highlighter: rouge

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Tom Schenk Jr.
  avatar: bio-photo.jpg
  email: "mailto:tomschenkjr@gmail.com"
  disqus-shortname:
  twitter: tomschenkjr
  facebook: #username
  github: tomschenkjr
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: tom-schenk-jr-65a80b92
  instagram: #username
  flickr: #username
  tumblr: datanouveau
  pinterest: #username
  orcid: 0000-0001-7533-1152
  google:
    plus: #username
    analytics:
    scholar: 19e5HrEAAAAJ
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  zotero: tomschenkjr

